swagger: "2.0"

info:
  title: "SubHub - Sub API"
  version: "1.0"

consumes:
  - "application/json"
produces:
  - "application/json"

basePath: /v1

securityDefinitions:
  PayApiKey:
    type: apiKey
    in: header
    name: Authorization
    description: |
      Ops issued token.
      An example of the Authorization header would be:
      ```Authorization: Bearer 00secret00```
    x-apikeyInfoFunc: src.shared.authentication.payment_auth
  SupportApiKey:
    type: apiKey
    in: header
    name: Authorization
    description: |
      Sending application identifier
    x-apikeyInfoFunc: src.shared.authentication.support_auth
parameters:
  uidParam:
    in: path
    name: uid
    type: string
    required: true
    description: User ID
  subIdParam:
    in: path
    name: sub_id
    type: string
    required: true
    description: Subscription ID
paths:
  /sub/version:
    get:
      operationId: src.shared.version.get_version
      tags:
        - Version
      summary: SubHub - Sub API Version
      description: Show Subhub version string (git describe --abbrev=7)
      produces:
        - application/json
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/Version'
  /sub/deployed:
    get:
      operationId: src.shared.deployed.get_deployed
      tags:
        - Deployed
      summary: SubHub deployed
      description: Show Subhub deployed env vars
      produces:
        - application/json
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/Deployed'
  /sub/support/{uid}/subscriptions:
    get:
      operationId: payments.support_status
      tags:
        - Support
      summary: Support view of user Subscriptions
      description: Get list of subscriptions for a premium payments customer
      security:
        - SupportApiKey: []
      produces:
        - application/json
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/Subscriptions'
        403:
          description: No subscriptions exist.
          schema:
            $ref: '#/definitions/Errormessage'
        404:
          description: Customer not found.
          schema:
            $ref: '#/definitions/Errormessage'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'
        503:
          description: Intermittent Error
          schema:
            $ref: '#/definitions/IntermittentError'
      parameters:
        - $ref: '#/parameters/uidParam'
  /sub/customer/{uid}/subscriptions:
    get:
      operationId: payments.subscription_status
      tags:
        - Subscriptions
      summary: List of Subscriptions
      description: Get list of subscriptions for a premium payments customer
      security:
        - PayApiKey: []
      produces:
        - application/json
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/Subscriptions'
        403:
          description: No subscriptions exist.
          schema:
            $ref: '#/definitions/Errormessage'
        404:
          description: Customer not found.
          schema:
            $ref: '#/definitions/Errormessage'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'
        503:
          description: Intermittent Error
          schema:
            $ref: '#/definitions/IntermittentError'
      parameters:
        - $ref: '#/parameters/uidParam'
    post:
      operationId: payments.subscribe_to_plan
      tags:
        - Subscriptions
      summary: Subscribe to Plan
      description: Subscribe to a Mozilla Plan
      security:
        - PayApiKey: []
      produces:
        - application/json
      responses:
        201:
          description: Subscription successful.
          schema:
            $ref: '#/definitions/Subscriptions'
        400:
          description: Error - missing paramenter or plan not valid
          schema:
            $ref: '#/definitions/Errormessage'
        402:
          description: Token not valid.
          schema:
            $ref: '#/definitions/Errormessage'
        409:
          description: Already subscribed.
          schema:
            $ref: '#/definitions/Errormessage'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'
        503:
          description: Intermittent Error
          schema:
            $ref: '#/definitions/IntermittentError'
      parameters:
        - $ref: '#/parameters/uidParam'
        - in: body
          name: data
          schema:
            type: object
            required:
              - pmt_token
              - plan_id
              - email
              - origin_system
              - display_name
            properties:
              pmt_token:
                type: string
                description: Pay Token.
                example: tok_KPte7942xySKBKyrBu11yEpf
              plan_id:
                type: string
                description: Plan ID.
                example: firefox_pro_basic_823
              email:
                type: string
                description: Email address.
                example: user@gmail.com
              origin_system:
                type: string
                description: Originating System.
                example: Firefox
              display_name:
                type: string
                description: User Display Name
                example: Joe User
  /sub/plans:
    get:
      operationId: payments.list_all_plans
      tags:
        - Subscriptions
      summary: List all Stripe Plans
      description: List all plans available from subscription provider
      security:
        - PayApiKey: []
      produces:
        - application/json
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/Plans'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'
        503:
          description: Intermittent Error
          schema:
            $ref: '#/definitions/IntermittentError'
  /sub/customer/{uid}/subscriptions/{sub_id}:
    post:
      operationId: payments.reactivate_subscription
      tags:
        - Subscriptions
      summary: Reactivate a Subscription
      description: Reactivate a subscription that's been cancelled but hasn't yet ended.
      security:
        - PayApiKey: []
      produces:
        - application/json
      responses:
        200:
          description: Subscription already active or reactivation successful.
          schema:
            type: object
            properties:
              message:
                type: string
        404:
          description: Subscription or User could not be found
          schema:
            $ref: '#/definitions/Errormessage'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'
        503:
          description: Intermittent Error
          schema:
            $ref: '#/definitions/IntermittentError'
      parameters:
        - $ref: '#/parameters/uidParam'
        - $ref: '#/parameters/subIdParam'
    delete:
      operationId: payments.cancel_subscription
      tags:
        - Subscriptions
      summary: Cancel a Subscription
      description: Cancel a Customers Subscription
      security:
        - PayApiKey: []
      produces:
        - application/json
      responses:
        201:
          description: Subscription cancellation successful.
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Error - missing paramenter.
          schema:
            $ref: '#/definitions/Errormessage'
        404:
          description: Customer does not exist or Subscription not valid.
          schema:
            $ref: '#/definitions/Errormessage'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'
        503:
          description: Intermittent Error
          schema:
            $ref: '#/definitions/IntermittentError'
      parameters:
        - $ref: '#/parameters/uidParam'
        - $ref: '#/parameters/subIdParam'
    patch:
      operationId: payments.update_subscription
      tags:
        - Subscriptions
      summary: Upgrade/Downgrade a Subscription
      description: Change the plan associated with a customer's subscription
      security:
        - PayApiKey: []
      produces:
        - application/json
      responses:
        200:
          description: Subscription upgrade/downgrade was successful
          schema:
            $ref: '#/definitions/Subscriptions'
        400:
          description: The Plan is not eligible for upgrade/downgrade
          schema:
            $ref: '#/definitions/ClientError'
        404:
          description: Subscription or User could not be found
          schema:
            $ref: '#/definitions/ClientError'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'
        503:
          description: Intermittent Error
          schema:
            $ref: '#/definitions/IntermittentError'
      parameters:
        - $ref: '#/parameters/uidParam'
        - $ref: '#/parameters/subIdParam'
        - in: body
          name: data
          schema:
            type: object
            required:
              - plan_id
            properties:
              plan_id:
                type: string
                description: New Plan ID
                example: plan_FxFGE9jvhYvCMe
  /sub/customer/{uid}:
    get:
      operationId: payments.customer_update
      tags:
        - Subscriptions
      summary: Customer Update
      description: Get updated customer subscription data.
      security:
        - PayApiKey: []
      produces:
        - application/json
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              cancel_at_period_end:
                type: boolean
              payment_type:
                type: string
                example: card
              last4:
                type: string
                example: 4242
              exp_month:
                type: integer
                example: 8
              exp_year:
                type: integer
                example: 2020
              subscriptions:
                type: array
                items:
                  $ref: '#/definitions/Subscriptions'

        400:
          description: Customer user ID does not match.
          schema:
            $ref: '#/definitions/Errormessage'
        404:
          description:  Customer does not exist.
          schema:
            $ref: '#/definitions/Errormessage'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'
        503:
          description: Intermittent Error
          schema:
            $ref: '#/definitions/IntermittentError'
      parameters:
        - $ref: '#/parameters/uidParam'
    post:
      operationId: payments.update_payment_method
      tags:
        - Subscriptions
      summary: Update Payment Method
      description: Update the credit card on file for a user's account.
      security:
        - PayApiKey: []
      produces:
        - application/json
      responses:
        201:
          description: Update successful.
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Error - unable to update payment method.
          schema:
            $ref: '#/definitions/Errormessage'
        404:
          description: Customer does not exist.
          schema:
            $ref: '#/definitions/Errormessage'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'
        503:
          description: Intermittent Error
          schema:
            $ref: '#/definitions/IntermittentError'
      parameters:
        - $ref: '#/parameters/uidParam'
        - in: body
          name: data
          schema:
            type: object
            required:
              - pmt_token
            properties:
              pmt_token:
                type: string
                description: Pay Token.
                example: tok_KPte7942xySKBKyrBu11yEpf
    delete:
      operationId: payments.delete_customer
      tags:
        - Subscriptions
      summary: Delete a customer
      description: |
        Delete customer records including database, payment providers, payment sources and active subscriptions
      security:
        - PayApiKey: []
      produces:
        - application/json
      responses:
        200:
          description: Customer deletion successful.
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Error - missing paramenter.
          schema:
            $ref: '#/definitions/Errormessage'
        404:
          description: Customer not found.
          schema:
            $ref: '#/definitions/Errormessage'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'
        503:
          description: Intermittent Error
          schema:
            $ref: '#/definitions/IntermittentError'
      parameters:
        - $ref: '#/parameters/uidParam'
definitions:
  Version:
    type: object
    properties:
      BRANCH:
        type: string
        example: master
      VERSION:
        type: string
        example: v0.0.3-11-gaf8af91
      REVISION:
        type: string
        example: af8af912255d204bcd178fe47e9a1af3215e09d4
  Deployed:
    type: object
    properties:
      DEPLOYED_BY:
        type: string
        example: sidler@76
      DEPLOYED_ENV:
        type: string
        example: dev
      DEPLOYED_WHEN:
        type: string
        example: 2019-07-26T21:21:16.180200
  Plans:
    type: array
    items:
      type: object
      properties:
        plan_id:
          type: string
          example: pro_basic_823
        product_id:
          type: string
          example: pro_basic
        product_name:
          type: string
          example: Moz Sub
        interval:
          type: string
          example: month
          enum:
            - day
            - week
            - month
            - year
        amount:
          type: integer
          example: 500
          description: A positive number in cents representing how much to charge on a recurring basis.
        currency:
          type: string
          example: usd
        plan_name:
          type: string
          example: Monthly Rocket Launches
        plan_metadata:
          type: object
          additionalProperties:
            type: string
        product_metadata:
          type: object
          additionalProperties:
            type: string
  Subscriptions:
    type: object
    properties:
      subscriptions:
        type: array
        required: [
          "subscription_id",
          "status",
          "plan_name",
          "plan_id",
          "ended_at",
          "current_period_start",
          "current_period_end",
          "cancel_at_period_end"
        ]
        items:
          type: object
          properties:
            subscription_id:
              type: string
              example: sub_abc123
            plan_id:
              type: string
              example: pro_basic_823
            plan_name:
              type: string
              example: "pro_basic"
            plan_metadata:
              type: object
              additionalProperties:
                type: string
            product_metadata:
              type: object
              additionalProperties:
                type: string
            current_period_end:
              type: number
              description: Seconds since UNIX epoch.
              example: 1557361022
            current_period_start:
              type: number
              description: Seconds since UNIX epoch.
              example: 1557361022
            end_at:
              type: number
              description: Non-null if the subscription is ending at a period in time.
              example: 1557361022
            status:
              type: string
              description: Subscription status.
              example: active
            cancel_at_period_end:
              type: boolean
              description: Shows if subscription will be cancelled at the end of the period.
              example: true
            failure_code:
              type: string
              description: Shows the failure code for subscription that is incomplete.  This is an optional field.
              example: Card declined
            failure_message:
              type: string
              description: Shows the failure message for subscription that is incomplete.  This is an optional field.
              example: Your card was declined.
  Errormessage:
    type: object
    properties:
      message:
        type: string
        example: The resource is not available.
      code:
        type: string
        example: 404
  ClientError:
    type: object
    properties:
      message:
        type: string
        example: Customer not found
      errno:
        type: integer
        example: 4000
  IntermittentError:
    type: object
    properties:
      message:
        type: string
        example: Connection cannot be completed.
  ServerError:
    type: object
    properties:
      message:
        type: string
        example: Server not available
      param:
        type: string
        example: Customer not found
      code:
        type: string
        example: Invalid Account
